name: inline_benchmarker
version: 1.0.0
authors:
- Hans Van den Keybus <hans@dotdotcommadot.com>
description: Inline Benchmarking Library
author: Hans Van den Keybus <hans@dotdotcommadot.com>
homepage: https://github.com/dotdotcommadot/dart_inline_benchmarker
environment:
  sdk: '>=2.0.0-dev <3.0.0'
web:
  compiler:
    debug: dartdevc
